-- Cópia de segurança: esquema completo da base de dados em SQL (tabelas, restrições, índices, RLS, políticas, permissões,
-- funções, gatilhos, agendamentos pg_cron e bucket), para reconstruir o projeto Supabase do zero.
-- Usada pela função backup (op schema); só a service_role a pode executar.
create or replace function public.backup_schema() returns text language plpgsql stable security definer set search_path = public, pg_catalog as $$
declare
  out text := '-- Cancioneiro: esquema da base de dados (gerado por public.backup_schema em ' || now()::text || E')\n'
           || E'-- Ordem: extensões, tabelas, restrições, índices, funções, RLS e políticas, permissões, gatilhos, agendamentos, armazenamento.\n\n';
  r record; cols text;
begin
  out := out || E'-- Extensões\n';
  for r in select extname from pg_extension where extname not in ('plpgsql') order by 1 loop
    out := out || format(E'create extension if not exists %I;\n', r.extname);
  end loop;

  out := out || E'\n-- Tabelas\n';
  for r in select c.oid, c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relkind = 'r' order by 2 loop
    select string_agg(format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
             case a.attidentity when 'a' then ' generated always as identity' when 'd' then ' generated by default as identity' else '' end,
             case when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
                  when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end,
             case when a.attnotnull then ' not null' else '' end), E',\n' order by a.attnum)
      into cols
      from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
      where a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped;
    out := out || format(E'create table if not exists public.%I (\n%s\n);\n', r.relname, cols);
  end loop;

  out := out || E'\n-- Restrições (chaves primárias e únicas primeiro, depois as estrangeiras e as verificações)\n';
  for r in select c.relname, k.conname, pg_get_constraintdef(k.oid) def from pg_constraint k join pg_class c on c.oid = k.conrelid
           join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' order by case k.contype when 'p' then 0 when 'u' then 1 when 'f' then 2 else 3 end, 1, 2 loop
    out := out || format(E'alter table public.%I add constraint %I %s;\n', r.relname, r.conname, r.def);
  end loop;

  out := out || E'\n-- Índices\n';
  for r in select pg_get_indexdef(i.indexrelid) def from pg_index i join pg_class c on c.oid = i.indrelid join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = 'public' and not exists (select 1 from pg_constraint k where k.conindid = i.indexrelid) order by 1 loop
    out := out || r.def || E';\n';
  end loop;

  out := out || E'\n-- Funções\n';
  for r in select p.oid, p.proname from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.prokind = 'f' order by 2 loop
    out := out || pg_get_functiondef(r.oid) || E';\n';
  end loop;

  out := out || E'\n-- Segurança ao nível das linhas (RLS) e políticas\n';
  for r in select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity order by 1 loop
    out := out || format(E'alter table public.%I enable row level security;\n', r.relname);
  end loop;
  for r in select * from pg_policies where schemaname = 'public' order by tablename, policyname loop
    out := out || format(E'create policy %I on public.%I as %s for %s to %s%s%s;\n', r.policyname, r.tablename, r.permissive, r.cmd,
      array_to_string(r.roles, ', '), coalesce(' using (' || r.qual || ')', ''), coalesce(' with check (' || r.with_check || ')', ''));
  end loop;

  out := out || E'\n-- Permissões (tabelas, colunas e funções) para anon e authenticated\n';
  out := out || E'revoke all on all tables in schema public from anon, authenticated;\n';
  for r in select table_name, grantee, string_agg(privilege_type, ', ' order by privilege_type) p from information_schema.role_table_grants
           where table_schema = 'public' and grantee in ('anon', 'authenticated') group by 1, 2 order by 1, 2 loop
    out := out || format(E'grant %s on public.%I to %s;\n', r.p, r.table_name, r.grantee);
  end loop;
  for r in select table_name, grantee, privilege_type, string_agg(quote_ident(column_name), ', ' order by column_name) cols from information_schema.column_privileges
           where table_schema = 'public' and grantee in ('anon', 'authenticated')
             and not exists (select 1 from information_schema.role_table_grants g where g.table_schema = 'public' and g.table_name = column_privileges.table_name
                             and g.grantee = column_privileges.grantee and g.privilege_type = column_privileges.privilege_type)
           group by 1, 2, 3 order by 1, 2, 3 loop
    out := out || format(E'grant %s (%s) on public.%I to %s;\n', r.privilege_type, r.cols, r.table_name, r.grantee);
  end loop;
  for r in select p.oid::regprocedure::text f, has_function_privilege('anon', p.oid, 'execute') a, has_function_privilege('authenticated', p.oid, 'execute') u
           from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.prokind = 'f' order by 1 loop
    out := out || format(E'revoke execute on function %s from public, anon, authenticated;\n', r.f);
    if r.u then out := out || format(E'grant execute on function %s to authenticated;\n', r.f); end if;
    if r.a then out := out || format(E'grant execute on function %s to anon;\n', r.f); end if;
  end loop;

  out := out || E'\n-- Gatilhos (também os de auth.users que chamam funções públicas)\n';
  for r in select pg_get_triggerdef(t.oid) def from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
           join pg_proc p on p.oid = t.tgfoid join pg_namespace pn on pn.oid = p.pronamespace
           where not t.tgisinternal and (n.nspname = 'public' or pn.nspname = 'public') order by 1 loop
    out := out || r.def || E';\n';
  end loop;

  out := out || E'\n-- Agendamentos (pg_cron)\n';
  for r in select jobname, schedule, command from cron.job order by 1 loop
    out := out || format(E'select cron.schedule(%L, %L, %L);\n', r.jobname, r.schedule, r.command);
  end loop;

  out := out || E'\n-- Armazenamento (bucket privado, sem políticas: só a service_role lhe acede)\n';
  for r in select id, public, file_size_limit, allowed_mime_types from storage.buckets order by 1 loop
    out := out || format(E'insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values (%L, %L, %L, %s, %L) on conflict (id) do nothing;\n',
      r.id, r.id, r.public, coalesce(r.file_size_limit::text, 'null'), r.allowed_mime_types);
  end loop;
  return out;
end $$;
revoke execute on function public.backup_schema() from public, anon, authenticated;
grant execute on function public.backup_schema() to service_role;

-- Lista dos ficheiros do bucket coro (para a cópia incremental saber o que mudou)
create or replace function public.backup_objects() returns table (name text, size bigint, etag text, updated_at timestamptz, mimetype text)
language sql stable security definer set search_path = public, storage as $$
  select o.name, (o.metadata->>'size')::bigint, o.metadata->>'eTag', o.updated_at, o.metadata->>'mimetype' from storage.objects o where o.bucket_id = 'coro' order by o.name
$$;
revoke execute on function public.backup_objects() from public, anon, authenticated;
grant execute on function public.backup_objects() to service_role;
